package main

import (
	"github.com/zboyco/GoWebAPI-JWT-Authorize/routers"
	"github.com/zboyco/GoWebAPI-JWT-Authorize/utils"
	"log"

	_ "github.com/zboyco/GoWebAPI-JWT-Authorize/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title WebAPI
// @version 0.0.1
// @description WebAPI v0.0.1

// @BasePath /
func main() {
	// 读取配置
	err := utils.ConfigInit()
	if err != nil {
		log.Panic(err)
	}

	// 连接数据库
	err = utils.DbInit()
	if err != nil {
		log.Panic("连接数据库失败:" + err.Error())
	}

	r := routers.InitRouter()
	r.Run()
}
