package main

import (
	"github.com/zboyco/GoWebAPI-JWT-Authorize/routers"

	_ "github.com/zboyco/GoWebAPI-JWT-Authorize/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title WebAPI
// @version 0.0.1
// @description WebAPI v0.0.1

// @BasePath /
func main() {
	r := routers.InitRouter()
	r.Run()
}
